### PR TITLE
Update the test sample of cornell_box

### PR DESCRIPTION
**Pull request by HK-SHAO**
for https://github.com/taichi-dev/taichi/pull/7252

### CODE REVIEW

**Comment by feisuzhu** [comment]
Waiting for 1000 frames is too long for every day CI job, is there any chance to reduce it to a number comparable to the old example (150 frames) ?

**Comment by HK-SHAO** [comment]
> Waiting for 1000 frames is too long for every day CI job, is there any chance to reduce it to a number comparable to the old example (150 frames) ?

OK! In my case the SAD is about `9.039757423151553` so I lowered the threshold to 20%
New commit

**Comment by feisuzhu** [comment]
Thanks~~~

**Comment by feisuzhu** [comment]
https://github.com/taichi-dev/taichi/pull/7252 No pingback?

**Pull request merged**
